services:
  - type: web
    name: nt-pushcut-approval-node
    env: docker
    plan: starter
    healthCheckPath: /health
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: .
    # Set the Root Directory in the Render UI to 'OrderManager/pushcut-server-node'
    # Or, if this render.yaml is at the repo root, uncomment the line below:
    # rootDir: ./OrderManager/pushcut-server-node
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      # RENDER_EXTERNAL_URL is automatically provided by Render,
      # so the server will correctly build chart URLs.
      - key: PORT
        value: 8000 